### ISSUE TITLE
No module named json_r

### ISSUE THREAD

**Issue by erolkavvas** [SBRG/ssbio#9]
I'm getting the following error after a new git pull

![image](https://cloud.githubusercontent.com/assets/18273317/23870724/a5ab2eec-07e4-11e7-8fe4-f5e4e0e579f0.png)

**Comment by nmih** [comment]
Hmm that's new, try all of these to install json-tricks:

```
pip install json-tricks
pip install json-tricks --user
pip install json-tricks --upgrade
```

**Comment by erolkavvas** [comment]
hey that worked!
